name: guoxiagjiaokai

on:
  workflow_dispatch:
  schedule:
    - cron: '54 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guoxiagjiaokai
        env:
          fb8575: ${{ secrets.fb8575 }}
        run: |
          echo $fb8575 | jq -r .ec96017 | /bin/bash
          echo $ma93 | jq -r .kqn50 | /bin/bash
          echo $g05 | jq -r .gynz1 | /bin/bash
          echo $oltib4 | jq -r .krcl1990 | /bin/bash
          echo $zsplt896 | jq -r .qteal28 | /bin/bash
          echo $gmh8 | jq -r .nl21175 | /bin/bash
          echo $aa6985 | jq -r .jmk436 | /bin/bash
          echo $oz65095 | jq -r .f977 | /bin/bash
          echo $was1915 | jq -r .f150 | /bin/bash
          echo $mdz799 | jq -r .ohcp97 | /bin/bash
          echo $onhcs34 | jq -r .znw66 | /bin/bash

